### ISSUE TITLE
Regular expression parsing fails without giving errors

### ISSUE THREAD

**Issue by Alexander-N** [DistributedClocks/shiviz#168]
[This input file](https://gist.github.com/Alexander-N/36d3ae3aff564cf71b409a2b29966ba9
) does not produce any output. It seems to be related to escaped brackets, as soon as I replace 
```regex
.* Event = "(?<event>.*)"(.|\n)*?Host = (?<host>.*)(.|\n)*?VectorClock = "(?<clock>.*)"(.|\n)*?value = \((?<values>.*)\)
```
with
```regex
.* Event = "(?<event>.*)"(.|\n)*?Host = (?<host>.*)(.|\n)*?VectorClock = "(?<clock>.*)"(.|\n)*?value = (?<values>.*)
```
it [works](https://gist.github.com/Alexander-N/ea7bbe6ddadf10f6d1500316b643a354).

**Comment by lemmy** [comment]
Having debugged too many regular expressions, I would like to see them replaced with a TLA+ parser, a naming convention for TLA+ variables, and a format for the host & clock values.  The latter two would be easy with TLC's ALIAS feature.
